#!/bin/bash
echo "======== informações do sistema =========="
# if [ $(uname -a) = 'uname -a' ]; 
echo "$(uname -a)"

echo "=== informações do usuário ==="
# if [ $(whoami) = 'root' ]; 
echo "Nome do usuário: $(whoami)"
# elif [ $(cd /) = '/' ]; 
echo "Diretório home: $HOME"
# elif [ $(pwd) = 'pwd' ]; 
echo "Diretório atual: $(pwd)"
# elif [ $(w -q) = 'w -q' ]; 
echo "Usuários logados: $(w -h)"
# fi
